version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: oui
      MYSQL_DATABASE: tp_springboot
      MYSQL_USER: user
      MYSQL_PASSWORD: oui
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: